# Logfile created on 2015-03-14 01:27:12 -0600 by logger.rb/47272
I, [2015-03-14T01:27:12.398911 #28158]  INFO -- : *** Below you'll find the most recent exception thrown, this will likely (but not certainly) be the exception that made your application exit abnormally ***
E, [2015-03-14T01:27:12.398954 #28158] ERROR -- : exit (SystemExit)
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.2/lib/rspec/core/runner.rb:39:in `exit'
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.2/lib/rspec/core/runner.rb:39:in `invoke'
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.2/exe/rspec:4:in `<top (required)>'
/home/scottp/.rbenv/versions/2.2.0/bin/rspec:23:in `load'
/home/scottp/.rbenv/versions/2.2.0/bin/rspec:23:in `<main>'
I, [2015-03-14T01:27:12.399009 #28158]  INFO -- : *** Below you'll find all the exception objects in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
E, [2015-03-14T01:27:12.400861 #28158] ERROR -- : stream closed (IOError)

E, [2015-03-14T01:27:12.401005 #28158] ERROR -- : failed to allocate memory (NoMemoryError)

E, [2015-03-14T01:27:12.401056 #28158] ERROR -- : stack level too deep (SystemStackError)

E, [2015-03-14T01:27:12.401171 #28158] ERROR -- : exception reentered (fatal)

E, [2015-03-14T01:27:12.404662 #28158] ERROR -- : ArgumentError (ArgumentError)

E, [2015-03-14T01:27:12.404905 #28158] ERROR -- : No such file or directory @ rb_sysopen - /home/scottp/workspace/i3-rbgen/log/backtrace-20150314012712-28158.log (Errno::ENOENT)
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/2.2.0/logger.rb:628:in `initialize'
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/2.2.0/logger.rb:628:in `open'
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/2.2.0/logger.rb:628:in `open_logfile'
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/2.2.0/logger.rb:584:in `initialize'
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/2.2.0/logger.rb:318:in `new'
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/2.2.0/logger.rb:318:in `initialize'
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/safely-0.3.2/lib/safely/backtrace.rb:24:in `new'
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/safely-0.3.2/lib/safely/backtrace.rb:24:in `log_exceptions'
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/safely-0.3.2/lib/safely/backtrace.rb:10:in `block in enable!'
E, [2015-03-14T01:27:12.405596 #28158] ERROR -- : exit (SystemExit)
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.2/lib/rspec/core/runner.rb:39:in `exit'
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.2/lib/rspec/core/runner.rb:39:in `invoke'
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.2/exe/rspec:4:in `<top (required)>'
/home/scottp/.rbenv/versions/2.2.0/bin/rspec:23:in `load'
/home/scottp/.rbenv/versions/2.2.0/bin/rspec:23:in `<main>'
E, [2015-03-14T01:27:12.405641 #28158] ERROR -- : File exists @ dir_s_mkdir - /home/scottp/workspace/i3-rbgen/tmp (Errno::EEXIST)
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir'
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/2.2.0/fileutils.rb:213:in `block in mkdir_p'
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/2.2.0/fileutils.rb:210:in `each'
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/guard-rspec-4.5.0/lib/guard/rspec_formatter.rb:89:in `_write'
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/guard-rspec-4.5.0/lib/guard/rspec_formatter.rb:79:in `write_summary'
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/guard-rspec-4.5.0/lib/guard/rspec_formatter.rb:64:in `dump_summary'
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.2/lib/rspec/core/reporter.rb:146:in `block in notify'
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.2/lib/rspec/core/reporter.rb:145:in `each'
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.2/lib/rspec/core/reporter.rb:145:in `notify'
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.2/lib/rspec/core/reporter.rb:130:in `finish'
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.2/lib/rspec/core/reporter.rb:64:in `report'
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.2/lib/rspec/core/runner.rb:108:in `run_specs'
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.2/lib/rspec/core/runner.rb:86:in `run'
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.2/lib/rspec/core/runner.rb:70:in `run'
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.2/lib/rspec/core/runner.rb:38:in `invoke'
/home/scottp/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.2/exe/rspec:4:in `<top (required)>'
/home/scottp/.rbenv/versions/2.2.0/bin/rspec:23:in `load'
/home/scottp/.rbenv/versions/2.2.0/bin/rspec:23:in `<main>'
E, [2015-03-14T01:27:12.405721 #28158] ERROR -- : Expected example to fail since it is pending, but it passed. (RSpec::Core::Pending::PendingExampleFixedError)
./spec/i3-rb_gen_spec.rb:7
